package Servelets;

import java.io.IOException;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import Services.PaymentDBUtil;

@WebServlet("/PaymentInsert")
public class PaymentInsert extends HttpServlet {
    private static final long serialVersionUID = 1L;
    
    // Handle GET requests to display the form with auto-generated fields
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        // Generate Payment ID
        String payID = PaymentDBUtil.getAutoGeneratedPayID();
        
        // Get Current Date
        Date currentDate = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dateStr = sdf.format(currentDate);
        
        // Generate Transaction ID
        String transactionID = PaymentDBUtil.getAutoGeneratedTransactionID();
        
        // Set attributes to pass to JSP
        request.setAttribute("payID", payID);
        request.setAttribute("dateStr", dateStr);
        request.setAttribute("transactionID", transactionID);
        
        // Forward to JSP form
        RequestDispatcher dispatcher = request.getRequestDispatcher("InsertPayment.jsp");
        dispatcher.forward(request, response);
    }
    
    // Handle POST requests to process the form submission
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        // Retrieve form parameters (including auto-generated fields)
        
        String dateStr = request.getParameter("date");
        BigDecimal amount = new BigDecimal(request.getParameter("amount"));
        String paymentMethod = request.getParameter("paymentMethod");
        String packageType = request.getParameter("packageType");
        
        
        
        // Insert payment details into the database
        boolean isTrue = PaymentDBUtil.insertPayment(dateStr, amount,paymentMethod, packageType);
        
        if(isTrue) {
        	response.sendRedirect("PaymentDetails.jsp");
        } else {
            RequestDispatcher dispatcher = request.getRequestDispatcher("unsuccess.jsp");
            dispatcher.forward(request, response);
        }
    }
}

